language: node_js
# Controlled by .nvmrc
#node_js:
#  - "4.2"

sudo: false

addons:
  sauce_connect:
    username:
      secure: REQoqTO96Ff6yF4z54W9Q6rDXzkkK7H8HKH2eqwdta3vCwXym1OdBXzzlrofaIQkFu60CbehnCOQNG2MOrP+YXYmt8zPGKrDARiF+f76bW52UPZeHM/JlMEDKnFwtTllzTZ3dH8vswenixPiZKDpdQkFjlO1VgWPZHSjVOe/FViXIOhic0mCJgPSEBuL1OH0FmyYkY9NSvRo+tHNE3E2MmlAKDy/GSiR6piIfm34J04sTDwRHFwPZauFTVS52PEuh1XNFg5maWkQzGYD7IFkjxglB7om7BjwHkSoSJhU7njx/6ROx/ERB+ktbaOfohW3S9WCSdeXscjwrqwy54tuyqiGkEZBGhSeVMTQadRLDU7S+sWAraf1vy+grKn24Bba2vqoEhhgYYQHRBsrTf10naYvz9H9d8LpaO6jS2YkL7QpcdKIsouAtI0p22u7E04qDEPx4O9bYUiPp5WmMZOu1o0aP1NF+UaLyFCggepMBmFgROUKeEYxgfFhYpaxvibRUsnojcrNyHPtdPMe3gcZiz3JJ9y1/7Z3FVvh2pX4S7kxh/dVcK/ICLVKHrU+UPvh5wixclqFYz0WUXDbjFwOVt+DksZLI1Ohhr0EJRceHkR3L82KYq6VRqo8iW5TfhNCYMd4PsdDzg9DRefrk0p96U4S+YUSKeBBa6ScGVuyu/c=
    access_key:
      secure: Z3cnG1RUsHtBx7OGHaZnAI8CWoOL4Vl1dZKT7q/d3O0gLT7yryggt+3u9ivRr/0Bu95o78wGefFo7fhPRYfJI5sZjvyAfPYvC2WugWiuY9BIHfbONBHglWkFjCYbf+EO20ItzAwUTllzKIKOD89rwtfnR84AYryWqr8GAye9nrupYrSD1wDf/Oqxa0J6rcCicgiwT2Dcb/J1BKFZ5lGaExnt8EgsOdCX7rNJdtHCskD0Ai3ecZWMsTuyTqXjD9q9W4YjCuAuCgTbJbXUBltePAh/+woIUhQS7NZo1dum7NpHTPDvMcMQuMzPJXnV3ywPldeHZkVW/bEMQOgf+PINqi0RKd5LW160Upmr0D6iZsSF0AePgxh8A8oGZM/7O++0Eu4zlMAPJ18IeRDRrM+WImyjnBR2e0shnf024XxU2fgc3f8MV8+bw0aP7+OwN9XaFTZRaL66EilpqRx4KPzTauZGGieWMnOQzhBZZ4gpJ8dXQIHDkAy4DPmB+2CaquT2VL6Tr8QIKbi04u+q17OsiTAXqMrr0HcW9NatL38sC/Aj/11QVKpnIw+Ktj04LBjUGkY0r2lSoiTQQByprHwDeXHPpevoJVj6ykrSBr+F1znF3SEHJrIMFN3lcH9RGhYvmO64EpQShJbx8yhyOGUBNxsFWg6epyGC02jWK0xT+6c=

script:
  - npm test
  - npm run selenium-install
  - npm run selenium-start &
  - sleep 1
  - BROWSER=phantomjs npm run uitest
  - USE_SAUCE=true BROWSER=chrome npm run uitest
  - USE_SAUCE=true BROWSER=firefox npm run uitest
  - USE_SAUCE=true BROWSER='internet explorer' BROWSER_VERSION=11 npm run uitest
  - USE_SAUCE=true BROWSER='internet explorer' BROWSER_VERSION=9 npm run uitest
  - USE_SAUCE=true BROWSER=safari PLATFORM=MAC npm run uitest

notifications:
  email: false

cache:
  directories:
    - node_modules
