app:
  image: mhart/alpine-node:5
  volumes:
    - ".:/app"
  ports:
    - "13000:3000"
  working_dir: /app
  environment:
    - NODE_ENV=production
  command: sh -c "echo 'Running on host machine at http://localhost:13000' && node server.js"

dev:
  build: .
  container_name: citizenship-appointment-client-dev
  dockerfile: docker/Dockerfile
  volumes:
    - "./dist:/app/dist:rw"
    - "./images:/app/images:ro"
    - "./lib:/app/lib:ro"
    - "./sass:/app/sass:ro"
    - "./views:/app/views:ro"
    - "./server.js:/app/server.js:ro"
    - "./webpack.config.js:/app/webpack.config.js:ro"
  ports:
    - "3000:3000"
    - "35729:35729"
  working_dir: /app

test:
  image: mhart/alpine-node:5
  volumes:
    - ".:/test"
  working_dir: /test
  command: ./node_modules/.bin/tape test/unit/*.js

selenium:
  image: selenium/standalone-${BROWSER}:2.52.0
  links:
    - app
  ports:
    - "14444:4444"

uitest:
  image: mhart/alpine-node:5
  environment:
    - BASE_URL=http://app:3000
    - SELENIUM_HOST=selenium
    - SELENIUM_PORT=4444
    - BROWSER=${BROWSER}
  links:
    - selenium
  volumes:
    - ".:/uitest"
  working_dir: /uitest
  command: ./node_modules/.bin/tape test/ui/loginAndBookAppointment.js

sauce-connect:
  image: ustwo/sauce-connect:4.3
  environment:
    - SAUCE_USERNAME=${SAUCE_USERNAME}
    - SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY}
  links:
    - app
  ports:
    - "14445:4445"
  command: -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY --tunnel-identifier $SAUCE_USERNAME

cross-browser-test:
  image: mhart/alpine-node:5
  environment:
    - SAUCE_USERNAME=${SAUCE_USERNAME}
    - SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY}
    - BASE_URL=http://app:3000
    - SELENIUM_HOST=sauce-connect
    - SELENIUM_PORT=4445
    - USE_SAUCE=true
    - BROWSER=${BROWSER}
    - BROWSER_VERSION=${BROWSER_VERSION}
    - PLATFORM=${PLATFORM}
  links:
    - sauce-connect
  volumes:
    - ".:/uitest"
  working_dir: /uitest
  command: sh -c "apk add --update bash && ./wait_for_it.sh sauce-connect:4445 -- ./cross_browser_test.sh"
